---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: instana-agent-operator
    app.kubernetes.io/version: 0.3.4
  name: agents.instana.io
spec:
  group: instana.io
  names:
    kind: InstanaAgent
    plural: agents
    shortNames:
    - ia
    singular: agent
  scope: Namespaced
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: instana-agent-operator
    app.kubernetes.io/version: 0.3.4
  name: instana-agent-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: instana-agent-operator
subjects:
- kind: ServiceAccount
  name: instana-agent-operator
  namespace: instana-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: instana-agent-operator
    app.kubernetes.io/version: 0.3.4
  name: instana-agent-operator
rules:
- apiGroups:
  - ''
  - extensions
  - apps
  - rbac.authorization.k8s.io
  resources:
  - serviceaccounts
  - clusterroles
  - clusterrolebindings
  - secrets
  - configmaps
  - daemonsets
  verbs:
  - list
  - watch
  - create
- apiGroups:
  - ''
  - apiextensions.k8s.io
  resources:
  - pods
  - customresourcedefinitions
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - instana.io
  resources:
  - agents
  verbs:
  - get
  - update
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - componentstatuses
  - endpoints
  - events
  - namespaces
  - nodes
  - pods
  - replicationcontrollers
  - resourcequotas
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - endpoints
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  - ingresses
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch