---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: instana-agent-operator
    app.kubernetes.io/version: 0.3.4
  name: instana-agent-operator
  namespace: instana-agent
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: instana-agent-operator
    app.kubernetes.io/version: 0.3.4
  name: instana-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: instana-agent-operator
    app.kubernetes.io/version: 0.3.4
  name: instana-agent-operator
  namespace: instana-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: instana-agent-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: instana-agent-operator
        app.kubernetes.io/version: 0.3.4
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TARGET_NAMESPACES
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['olm.targetNamespaces']
        image: instana/instana-agent-operator
        imagePullPolicy: Always
        name: instana-agent-operator
        ports:
        - containerPort: 8080
      serviceAccountName: instana-agent-operator